### ISSUE TITLE
Not working on firefox

### ISSUE THREAD

**Issue by michaelspeed** [adrianflutur/webviewx#74]
The webview does not load on firefox, anyone facing the same issue?

**Comment by gabrc52** [comment]
I can reproduce, it just flashes constantly:

![Screenshot from 2022-06-28 00-09-59](https://user-images.githubusercontent.com/24363938/176097621-bf87f863-b8a0-4d23-a68a-f27f7b19661b.png)

![Screenshot from 2022-06-28 00-10-00](https://user-images.githubusercontent.com/24363938/176097628-b894e17e-69b1-4140-82ad-97615c905430.png)

Console output:

```
Height of Platform View type: [_iframe_c23de61f_0ee9_4e85_b94b_0743f284efe6] may not be set. Defaulting to `height: 100%`.
Set `style.height` to any appropriate value to stop this message. [main.dart.js:44957:58](https://menu-chapingo.firebaseapp.com/admin/main.dart.js)
Width of Platform View type: [_iframe_c23de61f_0ee9_4e85_b94b_0743f284efe6] may not be set. Defaulting to `width: 100%`.
Set `style.width` to any appropriate value to stop this message. [main.dart.js:44957:58](https://menu-chapingo.firebaseapp.com/admin/main.dart.js)
NoSuchMethodError: s[a] is undefined [main.dart.js:29073:78](https://menu-chapingo.firebaseapp.com/admin/main.dart.js)
An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can remove its sandboxing.
```

**Comment by michaelspeed** [comment]
I just fixed this, because for some reason `about:blank` does not allow to load JS from other domains in firefox. So it kept re-initializing. In brief - `controller.loadHtml` will not work in firefox if the `html` is referencing a script in some other domains.

**Comment by akshay-appinventiv** [comment]
@michaelspeed can you tell what exactly you changed in code?

**Comment by gabrc52** [comment]
The latest commit in this repo is on Sep 2021. This issue was closed as completed on June 2022. Where is the code update?

**Comment by gabrc52** [comment]
@michaelspeed 

I am using controller.loadContent (from assets) but my HTML file does not reference any script in any other domain, but it still doesn't work.
